<?php require 'templates/layout/header.phtml' ?>

<?php if($error): ?>
    <div>
        <?=$error?>
    </div>
<?php endif ?>


<form action="login" method="POST">
    <div class="form-group">
        <label>email</label>
            <input type="email" name="email">
    </div>
    <div class="form-group">
        <label for="password">password</label>
            <input type="text" name="password">
    </div>
    <button type="submit">Login</button>
</form>

<?php require 'templates/layout/footer.phtml' ?>