<h1>Administrar tabla de plataformas</h1>

<form action="add_platform" method="POST">
    <div>
        <label>plataforma:</label>
            <input class="input-form-agregar" type="text" name="plataforma" required>
    </div>

    <div>
        <label>fabricante:</label>
         <input class="input-form-agregar" type="text" name="fabricante" required>
    </div>

    <div>
        <label>tipo:</label>
         <input class="input-form-agregar" type="text" name="tipo" required>
    </div>


    <button type="submit">Añadir</button>
</form>