<?php require 'templates/layout/header.phtml'; ?>

<section>
    <div>
        <h1>VIDEOGAMES STORE</h1>
        <p>
            En esta página se podrán comprar claves de VIDEOJUEGOS categorizados por PLATAFORMAS. Estamos en una etapa de desarrollo temprana por lo que todavía no se podrá comprar, solamente ver los VIDEOJUEGOS que estarán a la venta proximamente.
        </p>
    </div>
</section>

<?php require 'templates/layout/footer.phtml'; ?>