<?php require_once 'templates/layout/header.phtml'; ?>


<section>
    <h1>VIDEOJUEGOS</h1>
    <?php if(!empty($videogamesWithPlatforms)): ?>
        <ul>
        <?php foreach($videogamesWithPlatforms as $videogameWithPlatform): ?>
    <div class="div-lista-videojuegos">
        <a class="link-elemento-videojuego" href="view_detail_game/<?=htmlspecialchars($videogameWithPlatform->id_juego)?>">
        <li class="elemento-videojuego"><h2><?=htmlspecialchars($videogameWithPlatform->nombre)?></h2></li>
        <li class="elemento-videojuego">$<?= htmlspecialchars($videogameWithPlatform->precio)?></li>
        <li class="elemento-videojuego"><h3><?= htmlspecialchars($videogameWithPlatform->plataforma)?></h2></li>
        </a>
    </div>
        <?php endforeach ?>
        </ul>
    <?php else: ?>
        <p>No hay videojuegos en la lista.</p>
    <?php endif ?>
</section>


<?php require_once 'templates/layout/footer.phtml'; ?>